<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('journal_entries', function (Blueprint $table): void {
            $table->id();

            // Human-readable, year-sequenced code: e.g. "MISC/2026/0001",
            // "SALE/2026/0042". Generated by SequenceGenerator under a
            // row lock so concurrent inserts can't collide. Unique +
            // indexed for fast lookup-by-number.
            $table->string('number', 32)->unique();

            $table->date('date');

            // Free-text correlation field — e.g. POS order reference
            // ("POS/2026/0123") or a vendor bill number. Indexed for
            // back-lookup ("show me the journal entry for that POS sale").
            // Plain string, NO FK — origins span multiple modules.
            $table->string('reference')->nullable()->index();

            $table->text('narration')->nullable();

            // draft | posted — see Enums\JournalEntryState.
            $table->string('state', 16)->default('draft');

            // Audit: which user created it (a manual entry has one;
            // automated postings from POS / Purchases stamp the cashier
            // or buyer if the originating row carried it). Logical ref:
            // nullable, indexed, NO FK (cross-module isolation).
            $table->unsignedBigInteger('user_id')->nullable()->index();

            // Timestamp of the state->posted transition. NULL while draft.
            $table->timestamp('posted_at')->nullable();

            $table->timestamps();

            $table->index(['state', 'date']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('journal_entries');
    }
};
